module.exports = {
    STATUS_EMAIL_OK: "STATUS_EMAIL_OK",
    STATUS_EMAIL_FAIL: "STATUS_EMAIL_FAIL",
    STATUS_EMAIL_INVALID: "STATUS_EMAIL_INVALID",
    STATUS_OTP_OK: "STATUS_OTP_OK",
    STATUS_OTP_FAIL: "STATUS_OTP_FAIL",
    STATUS_OTP_TIMEOUT: "STATUS_OTP_TIMEOUT"
};